### ISSUE TITLE
Some DPL queries throw an NPE instead of printing SyntaxError

### ISSUE THREAD

**Issue by 51-code** [teragrep/pth_07#13]
**Describe the bug**

This query throws an NPE, even though the SyntaxError listener catches it.

```
| eval a=eval bc]
```

->

```
java.lang.NullPointerException
	at com.teragrep.pth_07.DPLExecutor$2.syntaxError(DPLExecutor.java:161)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:377)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenDeletion(DefaultErrorStrategy.java:548)
	at com.teragrep.pth_03.shaded.org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:266)
	at com.teragrep.pth_03.antlr.DPLParser.evalStatement(DPLParser.java:15504)
	at com.teragrep.pth_03.antlr.DPLParser.t_eval_evalParameter(DPLParser.java:35135)
	at com.teragrep.pth_03.antlr.DPLParser.evalTransformation(DPLParser.java:35067)
	at com.teragrep.pth_03.antlr.DPLParser.transformStatement(DPLParser.java:7342)
	at com.teragrep.pth_03.antlr.DPLParser.transformStatement(DPLParser.java:8073)
	at com.teragrep.pth_03.antlr.DPLParser.root(DPLParser.java:3128)
	at com.teragrep.pth_07.DPLExecutor.interpret(DPLExecutor.java:170)
	at com.teragrep.pth_07.DPLInterpreter.internalInterpret(DPLInterpreter.java:159)
``` 
 
**Expected behavior**

Should print the syntax error message.
 
**How to reproduce**

Run the query above.
 
**Screenshots**

 
**Software version**

pth_03 version: 5.11.0
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by StrongestNumber9** [comment]
Seems like nullcheck and extra logging should be done so we can catch and fix the underlying issues as well

**Comment by grafour** [comment]
how do you build this repo and reproduce this error?
