### ISSUE TITLE
ClassNotFoundException: com.teragrep.rlo_06.SDVector

### ISSUE THREAD

**Issue by StrongestNumber9** [teragrep/pth_07#22]
**Describe the bug**

Trying to use causes 

```
24/09/16 14:09:28 ERROR Executor: Exception in task 3.0 in stage 4.0 (TID 6)
java.lang.NoClassDefFoundError: com/teragrep/rlo_06/SDVector
<snip>
Caused by: java.lang.ClassNotFoundException: com.teragrep.rlo_06.SDVector
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 36 more
```

**Expected behavior**

Works

**How to reproduce**

Use it. My example simple kafka based notebook

**Screenshots**

 
**Software version**

pth_07-7.0.0-1
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

**Comment by StrongestNumber9** [comment]
Invalid issue, these should be removed instead
